version: '3.5'

networks:
    backend:
    frontend:

services:
  pg-database:
    container_name: postgres_container
    image: postgres:15.0
    env_file: ./database.env
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
        - backend
        - frontend

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file: ./database.env
    volumes:
       - pgadmin:/root/.pgadmin
       - ./servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
        - backend

volumes:
    postgres:
    pgadmin: